spring:
  application:
    name: config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          skipSslValidation: true
          uri: https://github.com/ly-w-97/test.git
          search-paths: config-repo
          username: 1250908570@qq.com
          password: Ly_591469958
          proxy:
            https:
              host: proxy2.xn.petrochina
              port: 8080
        native:
          default-label: master
      label: master
    bus:
      enabled: true
      trace:
        enabled: true
server:
  port: 12001
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8101/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
