spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ly-w-97/test.git # 配置git仓库的地址
          search-paths: test/config-repo # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: 1250908570@qq.com
          password: Ly_591469958
server:
  port: 12000
