spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8101/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug