server:
  port: 8102

spring:
  application:
    name: service-hi

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8101/eureka/
hystrix:
  metrics:
    enabled: true